### ISSUE TITLE
1.19.2 crash

### ISSUE THREAD

**Issue by Appolon24800** [SIMULATAN/meteor-notifications-addon#5]
I want to know if the addon work on 1.19.2 ? thx

**Comment by SIMULATAN** [comment]
[V2.0.0](https://github.com/SIMULATAN/meteor-notifications-addon/releases/tag/2.0.0) should work fine

**Comment by Appolon24800** [comment]
java.lang.NoSuchMethodError: 'meteordevelopment.meteorclient.settings.ColorSetting$Builder meteordevelopment.meteorclient.settings.ColorSetting$Builder.defaultValue(meteordevelopment.meteorclient.utils.render.color.SettingColor)'
	at com.github.simulatan.meteornotificationsaddon.hud.NotificationsHudElement.<init>(NotificationsHudElement.java:209)
	at meteordevelopment.meteorclient.systems.hud.HudElementInfo.create(HudElementInfo.java:53)
	at meteordevelopment.meteorclient.systems.hud.Hud.add(Hud.java:137)
	at meteordevelopment.meteorclient.systems.hud.Hud.add(Hud.java:141)
	at meteordevelopment.meteorclient.systems.hud.screens.AddHudElementScreen.runObject(AddHudElementScreen.java:124)
	at meteordevelopment.meteorclient.systems.hud.screens.AddHudElementScreen.lambda$initWidgets$6(AddHudElementScreen.java:100)
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:28)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.mouseReleased(WWidget.java:96)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25406(WidgetScreen.java:134)
	at net.minecraft.class_312.method_1605(class_312.java:96)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1208)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by SIMULATAN** [comment]
Well then, I'll debug this issue and come back to you once I have a solution

**Comment by Appolon24800** [comment]
https://mclo.gs/cf8W1TD

here is my crash log

**Comment by SIMULATAN** [comment]
Your meteor build is outdated, please update

**Comment by SIMULATAN** [comment]
Anything after [ebaebe7](https://github.com/MeteorDevelopment/meteor-client/commit/ebaebe7cfa5a787ea559cf22699cb1c13bc1c63f) should work (or, well, you'll have a different issue at least :sweat_smile:)
